name: Create GitHub Release

on:
  # Run on demand
  workflow_dispatch:

  # Run on push to main and when any of associated files are updated
  push:
    branches:
      - main
    paths:
      - Dockerfile.tools
      - '.github/workflows/dependabot_hack.yml'
      - 'providers/versions.tf'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - run: git fetch --tags --force origin  # WA: https://github.com/actions/checkout/issues/882
      - name: Create release
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974
        with:
          name: release/${{ github.sha }}
          tag_name: release/${{ github.sha }}
          generate_release_notes: true
          target_commitish: ${{ github.sha }}
          token: ${{ secrets.GH_RELEASES_TOKEN }}
