name: Create GitHub Release

on:
  # Run on demand
  workflow_dispatch:

  # Run on push to main and when any of associated files are updated
  push:
    branches:
      - main
    paths:
      - Dockerfile.tools
      - '.github/workflows/dependabot_hack.yml'
      - 'providers/versions.tf'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
      - run: git fetch --tags --force origin  # WA: https://github.com/actions/checkout/issues/882
      - name: Create release
        uses: softprops/action-gh-release@a74c6b72af54cfa997e81df42d94703d6313a2d0
        with:
          name: release/${{ github.sha }}
          tag_name: release/${{ github.sha }}
          generate_release_notes: true
          target_commitish: ${{ github.sha }}
          token: ${{ secrets.GH_RELEASES_TOKEN }}
