name: Create GitHub Release

on:
  # Run on demand
  workflow_dispatch:

  # Run on push to main and when any of associated files are updated
  push:
    branches:
      - main
    paths:
      - Dockerfile.tools
      - '.github/workflows/dependabot_hack.yml'
      - 'providers/versions.tf'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
        with:
          fetch-depth: 0
      - run: git fetch --tags --force origin  # WA: https://github.com/actions/checkout/issues/882
      - name: Create release
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564
        with:
          name: release/${{ github.sha }}
          tag_name: release/${{ github.sha }}
          generate_release_notes: true
          target_commitish: ${{ github.sha }}
          token: ${{ secrets.GH_RELEASES_TOKEN }}
