name: Create GitHub Release

on:
  # Run on demand
  workflow_dispatch:

  # Run on push to main and when any of associated files are updated
  push:
    branches:
      - main
    paths:
      - Dockerfile.tools
      - '.github/workflows/dependabot_hack.yml'
      - 'providers/versions.tf'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
        with:
          fetch-depth: 0
      - run: git fetch --tags --force origin  # WA: https://github.com/actions/checkout/issues/882
      - name: Create release
        uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87
        with:
          name: release/${{ github.sha }}
          tag_name: release/${{ github.sha }}
          generate_release_notes: true
          target_commitish: ${{ github.sha }}
          token: ${{ secrets.GH_RELEASES_TOKEN }}
