name: Create GitHub Release

on:
  # Run on demand
  workflow_dispatch:

  # Run on push to main when .bumpversion.cfg version is updated
  push:
    branches:
      - main
    paths:
      - Dockerfile.tools
      - 'providers/versions.tf'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          fetch-depth: 0
      - run: git fetch --tags --force origin  # WA: https://github.com/actions/checkout/issues/882
      - name: Test release condition
        id: release
        run: |
          RELEASE=false
          if make release/test 2> /dev/null; then RELEASE=true; fi
          echo "condition=${RELEASE}" >> "$GITHUB_OUTPUT"
          echo "version=$(make release/version)" >> "$GITHUB_OUTPUT"
      - name: Create release
        if: steps.release.outputs.condition == 'true'
        run: gh release create ${{ github.sha }} --generate-notes --target ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASES_TOKEN }}
